src/blueprints/General.py
from TheCodeLabs_BaseUtils.DefaultLogger import DefaultLogger
from flask import Blueprint, render_template, redirect, url_for

from logic import Constants
from logic.levels import LEVELS, GetLevel, LEVEL_SELECT
from logic.model import LevelSelectCell

LOGGER = DefaultLogger().create_logger_if_not_exists(Constants.APP_NAME)

NAME = 'gridPuzzle'


def construct_blueprint():
    general = Blueprint('general', __name__, static_folder='static')

    @general.route('/')
    def grid_puzzle():
        LOGGER.debug(f'New visit @ level select')

        levelSelectTutorial = LEVEL_SELECT[0]
        levelSelectGeneral = LEVEL_SELECT[1]
        numberOfTutorialLevels = LEVEL_SELECT[0]['numberOfLevels']

        return render_template(f'{NAME}LevelSelect.jinja2',
                               levelSelectTutorial=levelSelectTutorial['data'],
                               levelSelect=levelSelectGeneral['data'],
                               numberOfTutorialLevels=numberOfTutorialLevels)

    @general.route(f'/<int:levelNumber>')
    def grid_puzzle_level(levelNumber: int):
        if levelNumber < 0 or levelNumber >= len(LEVELS):
            return redirect(url_for('gridPuzzle.GridPuzzle'))

        LOGGER.debug(f'Level {levelNumber} started')

        level = GetLevel(levelNumber)
        levelData = level['data']
        endPosition = level['endPosition']
        hint = level['hint'] if 'hint' in level else ''

        levelDisplayName = __GetLevelDisplayName(levelNumber)
        numberOfTutorialLevels = LEVEL_SELECT[0]['numberOfLevels']

        return render_template(f'{NAME}.jinja2',
                               levelData=levelData,
                               endPosition=endPosition,
                               levelNumber=levelNumber,
                               levelDisplayName=levelDisplayName,
                               numberOfTutorialLevels=numberOfTutorialLevels,
                               hint=hint)

    def __GetLevelDisplayName(levelNumber: int) -> str:
        levelSelectTutorial = LEVEL_SELECT[0]
        levelSelectGeneral = LEVEL_SELECT[1]

        levelCellsTutorial = [element for element in levelSelectTutorial['data'].values() if
                              isinstance(element, LevelSelectCell)]
        levelCellsGeneral = [element for element in levelSelectGeneral['data'].values() if
                             isinstance(element, LevelSelectCell)]
        levelCells = levelCellsTutorial + levelCellsGeneral
        return [cell for cell in levelCells if cell.levelNumber == levelNumber][0].levelDisplayName

    return general

src/templates/gridPuzzle.jinja2
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>GridPuzzle</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/gridPuzzle.css') }}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% import 'gridPuzzleMacros.jinja2' as gridPuzzleMacros %}

        {% set isEndOnLeftSide = false %}
        {% if endPosition[1] == 0 %}
            {% set isEndOnLeftSide = true %}
        {% endif %}

        <div id="main">
            <div id="header">
                <div id="headline">{{ levelDisplayName }}</div>
                <a href="{{ url_for('general.grid_puzzle') }}" id="button-back">Level Select</a>
            </div>

            <div class="grid-container" data-level-number="{{ levelNumber }}">
                <div class="grid" id="layer-1">
                    {{ gridPuzzleMacros.drawGrid(levelData, true) }}

                {{ gridPuzzleMacros.drawStart(isEndOnLeftSide, false) }}

                    <div id="layer-2">
                        {{ gridPuzzleMacros.drawGrid(levelData, false) }}

                        {{ gridPuzzleMacros.drawStart(isEndOnLeftSide, true) }}
                    </div>
                </div>
            </div>

            <div id="buttons">
                <div id="button-hint" class="hidden hint-button">Need a hint?</div>
                <div id="hint" class="hidden"><span id="hint-start">Hint:</span> <span id="hint-text">{{ hint}}</span></div>

                <div id="reset">
                    <img class="arrow-button" id="button-reset" src="{{ url_for('static', filename='/images/R_Key.png') }}"/>
                    <div>= Reset</div>
                </div>

                <img class="arrow-button" id="button-up" src="{{ url_for('static', filename='/images/Arrow_Up.png') }}"/>
                <div class="arrow-buttons-bottom">
                    <img class="arrow-button" id="button-left" src="{{ url_for('static', filename='/images/Arrow_Left.png') }}"/>
                    <img class="arrow-button" id="button-down" src="{{ url_for('static', filename='/images/Arrow_Down.png') }}"/>
                    <img class="arrow-button" id="button-right" src="{{ url_for('static', filename='/images/Arrow_Right.png') }}"/>
                </div>
            </div>

            <div id="level-select-spacer">&nbsp;</div>

            <script>
                numberOfTutorialLevels = {{ numberOfTutorialLevels }};
            </script>
        </div>

        <script defer src="{{ url_for('static', filename='libs/socket.io.min.js') }}" type="text/javascript"></script>
        <script defer src="{{ url_for('static', filename='js/common.js') }}" type="text/javascript"></script>
        <script defer src="{{ url_for('static', filename='js/gridPuzzle.js') }}" type="text/javascript"></script>
    </body>
</html>

src/templates/gridPuzzleLevelSelect.jinja2
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>GridPuzzle</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/gridPuzzle.css') }}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>

        {% import 'gridPuzzleMacros.jinja2' as gridPuzzleMacros %}

        <div id="main-level-select">
            <div id="header">
                <div id="headline">Gridpuzzle</div>
            </div>

            <div id="headline-level-select">Tutorial</div>
            <div class="grid-container">
                <div class="grid">
                    {{ gridPuzzleMacros.drawGrid(levelSelectTutorial, true, userGameData, true) }}

                    {{ gridPuzzleMacros.drawStart(false, false) }}
                </div>
            </div>

            <div id="headline-level-select">Levels</div>

            <div class="grid-container" id="container-level-select">
                <div class="grid">
                    {{ gridPuzzleMacros.drawGrid(levelSelect, true, userGameData) }}

                    {{ gridPuzzleMacros.drawStart(false, false) }}
                </div>
            </div>

            <div id="level-select-spacer">&nbsp;</div>

            <div id="tutorial-notice">- Complete Tutorial first -</div>
        </div>

        <script>
            numberOfTutorialLevels = {{ numberOfTutorialLevels }};
        </script>

        <script defer src="{{ url_for('static', filename='libs/socket.io.min.js') }}" type="text/javascript"></script>
        <script defer src="{{ url_for('static', filename='js/common.js') }}" type="text/javascript"></script>
        <script defer src="{{ url_for('static', filename='js/levelSelect.js') }}" type="text/javascript"></script>
    </body>
</html>

src/templates/gridPuzzleMacros.jinja2
{% macro drawGrid(gridData, renderPuzzleElements, userGameData=None, isTutorial=false) -%}
    {% set lastRow = namespace(value=-1) %}

    {% for position, item in gridData.items() %}
        {% if position[0] > lastRow.value %}
            {% if not loop.first %}
                </div>
            {% endif %}

            <div class="row">
            {% set lastRow.value = position[0] %}
        {% endif %}

        {% if item.__class__.__name__ == 'Corner' %}
            {{ drawCorner(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EdgeHorizontal' %}
            {{ drawEdgeHorizontal(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EdgeVertical' %}
            {{ drawEdgeVertical(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EdgeGapHorizontal' %}
            {{ drawEdgeGapHorizontal(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EdgeGapVertical' %}
            {{ drawEdgeGapVertical(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'Cell' %}
            {{ drawCell(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EndRight' %}
            {{ drawEnd(position, item, renderPuzzleElements, 'end-right') }}
        {% elif item.__class__.__name__ == 'EndTop' %}
            {{ drawEnd(position, item, renderPuzzleElements, 'end-top') }}
        {% elif item.__class__.__name__ == 'EndLeft' %}
            {{ drawEnd(position, item, renderPuzzleElements, 'end-left') }}
        {% elif item.__class__.__name__ == 'EndSpaceHorizontal' %}
            {{ drawEndSpaceHorizontal(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EndSpaceVertical' %}
            {{ drawEndSpaceVertical(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'EndSpaceVerticalCell' %}
            {{ drawEndSpaceVerticalCell(position, item, renderPuzzleElements) }}
        {% elif item.__class__.__name__ == 'LevelSelectCell' %}
            {{ drawLevelSelectCell(position, item, userGameData, isTutorial) }}
        {% endif %}

        {% if loop.last %}
            </div>
        {% endif %}
    {% endfor %}
{% endmacro -%}


{% macro drawCorner(position, item, renderPuzzleElements) -%}
    <div class="edge edge-corner {{ item.GetStyle() }}" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        {% if item.isMandatory and renderPuzzleElements %}
            {{ dot() }}
        {% endif %}
    </div>
{% endmacro -%}

{% macro drawEdgeHorizontal(position, item, renderPuzzleElements) -%}
    <div class="edge edge-horizontal" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        {% if item.isMandatory and renderPuzzleElements %}
            {{ dot() }}
        {% endif %}
    </div>
{% endmacro -%}

{% macro drawEdgeGapHorizontal(position, item, renderPuzzleElements) -%}
    <div class="edge edge-horizontal edge-gap edge-gap-horizontal" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        <div class="edge-gap-end-right"></div>
        <div class="edge-gap-end-left"></div>
    </div>
{% endmacro -%}

{% macro drawEdgeVertical(position, item, renderPuzzleElements) -%}
    <div class="edge edge-vertical" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        {% if item.isMandatory and renderPuzzleElements %}
            {{ dot() }}
        {% endif %}
    </div>
{% endmacro -%}

{% macro drawEdgeGapVertical(position, item, renderPuzzleElements) -%}
    <div class="edge edge-vertical edge-gap edge-gap-vertical" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        <div class="edge-gap-end-bottom"></div>
        <div class="edge-gap-end-top"></div>
    </div>
{% endmacro -%}

{% macro drawCell(position, item, renderPuzzleElements) -%}
    <div class="cell" data-row="{{ position[0] }}" data-column="{{ position[1] }}">
        {% if renderPuzzleElements %}
            {% if item.square is not none %}
                <div class="square square-{{ item.square.color }}"></div>
            {% endif %}

            {% for __ in range(item.numberOfTriangles) %}
                <div class="triangle"></div>
            {% endfor %}
        {% endif %}
    </div>
{% endmacro -%}

{% macro dot() -%}
    <div class="dot"></div>
{% endmacro -%}

{% macro drawEnd(position, item, renderPuzzleElements, className) -%}
    <div class="edge end {{ className }}" data-row="{{ position[0] }}" data-column="{{ position[1] }}"></div>
{% endmacro -%}

{% macro drawEndSpaceHorizontal(position, item, renderPuzzleElements) -%}
    <div class="end-space-horizontal" data-row="{{ position[0] }}" data-column="{{ position[1] }}"></div>
{% endmacro -%}

{% macro drawEndSpaceVertical(position, item, renderPuzzleElements) -%}
    <div class="end-space-vertical" data-row="{{ position[0] }}" data-column="{{ position[1] }}"></div>
{% endmacro -%}

{% macro drawEndSpaceVerticalCell(position, item, renderPuzzleElements) -%}
    <div class="end-space-vertical-cell" data-row="{{ position[0] }}" data-column="{{ position[1] }}"></div>
{% endmacro -%}

{% macro drawStart(isEndOnLeftSide, highlight) -%}
    <div class="edge start {% if isEndOnLeftSide %}start-shifted{% endif %} {% if highlight %}edge-highlight{% endif %}"></div>
{% endmacro -%}

{% macro drawLevelSelectCell(position, item, userGameData, isTutorial) -%}
    <a href="{{ url_for('general.grid_puzzle_level', levelNumber=item.levelNumber) }}"
       class="cell level-select-cell"
       data-row="{{ position[0] }}"
       data-column="{{ position[1] }}"
       data-level-number="{{ item.levelNumber }}"
       data-is-tutorial="{{ isTutorial | int }}">
        {{ item.levelShortDisplayName }}
    </a>
{% endmacro -%}

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>GrizPuzzle</title>
    </head>
    <body>

    </body>
</html>